// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKuao1ZArELaBsUx8pTvG7eElspoOUCWg',
    appId: '1:153034379474:web:a17fb65574132d3571dd0b',
    messagingSenderId: '153034379474',
    projectId: 'doctor-booking-system-ef2c8',
    authDomain: 'doctor-booking-system-ef2c8.firebaseapp.com',
    storageBucket: 'doctor-booking-system-ef2c8.firebasestorage.app',
    measurementId: 'G-NNGJKSGC4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYERZzdkjTkY9QNZLR81UeBvSgYPJzswQ',
    appId: '1:153034379474:android:456b0864a388295c71dd0b',
    messagingSenderId: '153034379474',
    projectId: 'doctor-booking-system-ef2c8',
    storageBucket: 'doctor-booking-system-ef2c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm-Lu7Kn0gbI1WlesFOjElegbHvdA954w',
    appId: '1:153034379474:ios:0dd8390c9a074c5271dd0b',
    messagingSenderId: '153034379474',
    projectId: 'doctor-booking-system-ef2c8',
    storageBucket: 'doctor-booking-system-ef2c8.firebasestorage.app',
    iosBundleId: 'com.example.dbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm-Lu7Kn0gbI1WlesFOjElegbHvdA954w',
    appId: '1:153034379474:ios:0dd8390c9a074c5271dd0b',
    messagingSenderId: '153034379474',
    projectId: 'doctor-booking-system-ef2c8',
    storageBucket: 'doctor-booking-system-ef2c8.firebasestorage.app',
    iosBundleId: 'com.example.dbs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKuao1ZArELaBsUx8pTvG7eElspoOUCWg',
    appId: '1:153034379474:web:795feb0d0154316171dd0b',
    messagingSenderId: '153034379474',
    projectId: 'doctor-booking-system-ef2c8',
    authDomain: 'doctor-booking-system-ef2c8.firebaseapp.com',
    storageBucket: 'doctor-booking-system-ef2c8.firebasestorage.app',
    measurementId: 'G-1D35YBS3LG',
  );
}
